---
title: Modellflugclub Berlin e.V.
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: assets/**/*
  values:
    sitemap: false
motto: In der Natur – Mit der Natur – Für die Natur
author: HUMMELFLUG Modellflugclub Berlin e.V.
email: hummelflieger@arcor.de
description: |-
  Unser Motto ist „Just for Fun“. Also keinen Stress. Freizeit genießen, fliegen, plaudern, Bierchen, Bratwurst und viel frische Luft.

  Interessenten sind immer gern gesehen. Wir helfen beim ersten Start und geben auch kostenlosen Flugunterricht.
baseurl: 
url: https://www.mfc-hummelflug.de
theme: minima
minima:
  date_format: "%d.%m.%Y"
show_excerpts: true
lang: de
rss: RSS Feed
header_pages:
- about.markdown
- flying-field.markdown
- models.markdown
- calendar.markdown
responsive_image:
  template: _includes/responsive-image.html
  default_quality: 90
  sizes:
  - width: 364
  - width: 530
  - width: 740
  - width: 1400
  auto_rotate: true
  strip: true
  base_path: assets/galleries
  output_path_format: assets/galleries/%{dirname}/%{width}/%{basename}
  save_to_source: false
plugins:
- jekyll-last-modified-at
- jekyll-feed
- jekyll-sitemap
- jekyll-responsive-image
exclude:
- ".rvmrc"
- ".sass-cache/"
- ".jekyll-cache/"
- ".travis.yml"
- gemfiles/
- README.md
- assets/galleries/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
