---
title: Hummelflug Modellflugclub Berlin e.V.
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hummelflieger@arcor.de
description: |-
  Unser Motto ist „Just for Fun“. Also keinen Stress. Freizeit genießen, fliegen, plaudern, Bierchen, Bratwurst und viel frische Luft.

  Dazu steht uns eine 200 m lange und 80 m breite Landebahn zur Verfügung. Unser Platz liegt in herrlicher grüner Natur. Es stehen Bänke, ein Grillplatz, ein großer Tisch und eine Wasserpumpe zur Verfügung.

  Interessenten sind immer gern gesehen. Wir helfen beim ersten Start und geben auch kostenlosen Flugunterricht.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
exclude:
- ".rvmrc"
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- README.md
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
