---
title: Modellflugclub Berlin e.V.
author: HUMMELFLUG Modellflugclub Berlin e.V.
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hummelflieger@arcor.de
description: |-
  Unser Motto ist „Just for Fun“. Also keinen Stress. Freizeit genießen, fliegen, plaudern, Bierchen, Bratwurst und viel frische Luft.

  Interessenten sind immer gern gesehen. Wir helfen beim ersten Start und geben auch kostenlosen Flugunterricht.
baseurl:
url:
theme: minima
minima:
  date_format: "%d.%m.%Y"
show_excerpts: true
lang: de
rss: RSS Feed
header_pages:
  - about.markdown
  - contact.markdown
  - flying-field.markdown
  - calendar.markdown
  - links.markdown
plugins:
- jekyll-feed
exclude:
- ".rvmrc"
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- README.md
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
